In [106]:
import pandas
import numpy as np
import random

# 数据读取
data = pandas.read_csv("data/iris.data",header=None)

# 获取数据基本信息
n_samples, n_features = data.shape

# 类别
y = data.values[:,n_features-1]
X = data.values[:,0:n_features-1]

# 基本数据
samples, features = X.shape

# 类别数，为了方便对结果进行校验，去k=实际类别数
n_class = len(set(y))
k = n_class

# 归一化处理
X = (X - X.min())/(X.max()-X.min())

# 中心点选取(随机选择k个点作为中心点)
mid = np.array(random.sample(list(X),k))

# 循环次数（TODO:变化小于一定范围停止循环）
max_epoch = 1000000

# 初始化预测值
predict = np.array(np.zeros((1, samples)))

# 通过计算距离得到每个点的最近中心点，判断类别
def run(predict):
    temp = np.sum((X - mid[0])**2,axis=1)
    for i in range(1,k):    
        temp_sum = np.sum((X - mid[i])**2,axis=1)
        predict = np.where(temp < temp_sum, predict, i )
        temp = np.where(temp < temp_sum, temp, temp_sum)
    return predict

In [107]:
for i in range(0, max_epoch):
    for j in range(0,k):
        predict = run(predict)
        mid[j] = np.sum(np.where(predict.T==j, X, 0), axis=0)/list(predict[0]).count(j)

In [108]:
predict

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1.,
        1., 2., 2., 1., 1., 1., 1., 2., 1., 2., 1., 2., 1., 1., 2., 2.,
        1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 2., 1.,
        1., 1., 2., 1., 1., 2.]])

In [114]:
# 可以对数组按类别排序后再进行结果的比对，不过这里的数据集已经是有序的了
print(list(y).count(list(set(y))[0]))
print(list(y).count(list(set(y))[1]))
print(list(y).count(list(set(y))[2]))

50
50
50


In [110]:
predict[0][0:50]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
predict[0][50:100]

array([2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [112]:
# 最后一类错误率较高
predict[0][100:150]

array([1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1.,
       1., 1., 2., 1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2.,
       1., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])